name: gedit310
version: 1
summary: Old School gedit
description: Old school gedit for the toolbar aficionado
confinement: devmode  # use "strict" to enforce system access only via declared interfaces

apps:
    gedit310:
        #command:  gtk-launch gedit
        command:  desktop-launch gedit
        plugs: [x11, unity7, home, gsettings]

parts:
    gedit:
        plugin: autotools
        source: https://git.gnome.org/browse/gedit
        source-branch: gnome-3-10
        source-type: git
        #install-via: prefix
        configflags:  [--prefix=/snap/gedit310/current/usr, --disable-gtk-doc, --disable-introspection]
        organize:
            snap/gedit310/current/usr: usr
        build-packages:
            -    libffi-dev
            -    cdbs
            -    gobject-introspection
            -    gsettings-desktop-schemas-dev
            -    intltool
            -    iso-codes
            -    libenchant-dev
            -    libgirepository1.0-dev
            -    libglib2.0-dev
            -    libgtk-3-dev
            -    libgtksourceview-3.0-dev
            -    libpeas-dev
            -    libx11-dev
            -    libxml2-dev
            -    gtk-doc-tools
            -    yelp-tools

    deb:
        plugin: nil
        after: [desktop/gtk3]
        #after: [gtkconf]
        stage-packages:
            -   python3
            -   libatk1.0-0
            -   libcairo2
            -   libenchant1c2a
            -   libgdk-pixbuf2.0-0
            -   libgirepository-1.0-1
            -   libglib2.0-0
            -   libgtk-3-0
            -   libgtksourceview-3.0-1
            -   libpango-1.0-0
            -   libpeas-1.0-0
            -   libx11-6
            -   libxml2
            -   gir1.2-gtk-3.0
            -   gsettings-desktop-schemas
            -   python3-gi
            -   python3-gi-cairo
            -   gir1.2-peas-1.0
            -   gir1.2-glib-2.0
            -   gir1.2-pango-1.0
            -   libpeas-1.0-0-python3loader
            -   iso-codes
            -   light-themes
            #   For schemas to compile
            -   libglib2.0-bin
            #   For dconf to work
            -   dconf-gsettings-backend
            -   unity-gtk3-module 
#            -   gedit-source-code-browser-plugin
#            -   gedit-plugins
#            -   gedit-latex-plugin
#            -   gedit-developer-plugins

